### ISSUE TITLE
I still cannot scan QR code even in version 0.7.0

### ISSUE THREAD

**Issue by offchan42** [perishllc/nautilus#3] opened 2022-11-12 17:33 UTC
I can scan my sendnano.com wallet in Natrium but not in Nautilus.
After I scanned the QR code, nothing happened. The address box was not filled.
![image](https://user-images.githubusercontent.com/15215732/201487046-2a2c7c21-0b87-473e-89bf-97826045be7b.png)

**Comment by fossephate** [comment] 2022-11-12 18:36
I'll need some more details about what iOS / Android version you're running as I can't reproduce the issue

If you're running android be sure to let me know what model / flavor of Android it is ex. OxygenOS or if it's a pixel / w/e

**Comment by offchan42** [comment] 2022-11-12 20:30
I use iOS 15.6.1 on iPhone X.

**Comment by fossephate** [comment] 2022-11-12 20:58
Found the bug! it'll be fixed in the next release
In the meantime, swiping up on the send button to scan still works! (Which is usually how I do it and why I didn't find the bug at first lol)

**Comment by offchan42** [comment] 2022-11-13 08:00
Hmm, swiping up is a cool feature. I didn't know that exist. Cool! I'll wait until the next release then. Thanks!

**Closed as completed** 2022-11-13 13:39 UTC
